apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: taki-demo
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "takidemo"
  DB_USER: "takidemo"
  CORS_ALLOWED_ORIGINS: "http://localhost,http://localhost:5173"
  JWT_EXPIRATION_MS: "86400000"
